REM INSERTING into GL_TIPOS_PERSONAS
SET DEFINE OFF;
Insert into GL_TIPOS_PERSONAS (ID,DESCRIPCION) values ('N ','Natural');
Insert into GL_TIPOS_PERSONAS (ID,DESCRIPCION) values ('J ','Jurídica');
Insert into GL_TIPOS_PERSONAS (ID,DESCRIPCION) values ('UO','Unidad Organizacional');
Insert into GL_TIPOS_PERSONAS (ID,DESCRIPCION) values ('S ','Sistema');

REM INSERTING into GL_TIPOS_DOCIDENT
SET DEFINE OFF;
Insert into GL_TIPOS_DOCIDENT (ID,DESCRIPCION,SIGLAS) values ('1','Cédula de Identidad Venezolana','C.I.');
Insert into GL_TIPOS_DOCIDENT (ID,DESCRIPCION,SIGLAS) values ('2','Registro de Información Fiscal','R.I.F.');

REM INSERTING into GL_PREFIJO_DOCID
SET DEFINE OFF;
Insert into GL_PREFIJO_DOCID (ID,COD_PREFIJO,TP_PER_ID,DESCRIPCION) values ('1','V','N ','Venezolano');
Insert into GL_PREFIJO_DOCID (ID,COD_PREFIJO,TP_PER_ID,DESCRIPCION) values ('2','E','N ','Extranjero');
Insert into GL_PREFIJO_DOCID (ID,COD_PREFIJO,TP_PER_ID,DESCRIPCION) values ('3','P','N ','Pasaporte');

REM INSERTING into GL_PREFIJOS_TIPO_DOCID
SET DEFINE OFF;
Insert into GL_PREFIJOS_TIPO_DOCID (TP_DOCID_ID,PREF_DOCID_ID) values ('1','1');


REM INSERTING into GL_PERSONAS
SET DEFINE OFF;
Insert into GL_PERSONAS (ID,TP_PER_ID,NOMBRE,INSTANCIAS) values ('1','S ','Administrador del Sistema','USUARIO');

REM INSERTING into SG_USUARIOS
SET DEFINE OFF;
Insert into SG_USUARIOS (ID,LOGIN,CLAVE,CREADO_EL,EXPIRADO,BLOQUEADO,FEC_CAMBIO_CLAVE,FEC_ULT_ENTRADA,ACTIVO,CREADO_POR,MODIFICADO_EL,MODIFICADO_POR,INTENTOS) values ('1','administrador','1BF9F3EFBE7ADA15BB98B090749C10EFE7BB106A25335641',to_date('13/11/19','DD/MM/RR'),'N','N',null,to_date('06/02/20','DD/MM/RR'),'S','PROYECTO',to_date('06/02/20','DD/MM/RR'),'nobody','0');

