ALTER TABLE EVENTOS 
DROP COLUMN IN_CURSO;

ALTER TABLE EVENTOS 
DROP COLUMN IN_SECCION;

ALTER TABLE EVENTOS 
DROP COLUMN IN_MONTO;

ALTER TABLE EVENTOS 
DROP COLUMN IN_CANTIDAD;

ALTER TABLE EVENTOS 
DROP COLUMN IN_EVALUACION;

ALTER TABLE EVENTOS 
ADD (TIPO_EVENTO VARCHAR2(5) );

COMMENT ON COLUMN EVENTOS.TIPO_EVENTO IS 'TIPO DE EVENTO EJ. ACADEMICO ACAD, ADMINISTRATIVO ADM';

--------------------------------------------------------
--  DDL for Table HOJA_VIDA_EST
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."HOJA_VIDA_EST" 
   (	"ID" NUMBER, 
	"MATRICULA" NUMBER, 
	"EVENTO_ID" NUMBER, 
	"FECHA" TIMESTAMP (6) DEFAULT systimestamp, 
	"METADATA" CLOB, 
	"OBSERVACION" VARCHAR2(4000 BYTE)
   );
--------------------------------------------------------
--  DDL for Index HOJA_VIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."HOJA_VIDA_PK" ON "FUNDAUC"."HOJA_VIDA_EST" ("ID");
--------------------------------------------------------
--  Constraints for Table HOJA_VIDA_EST
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST" ADD CONSTRAINT "HOJA_VIDA_PK" PRIMARY KEY ("ID");
  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST" ADD CONSTRAINT "HOJA_VIDA_EST_CHK1" CHECK (metadata is json) ENABLE;

ALTER TABLE INSCRIPCIONES  
ADD (ES_EXONERADO CHAR(1) DEFAULT 'N' );

ALTER TABLE INSCRIPCIONES  
MODIFY (FECHA_INS DEFAULT sysdate );

COMMENT ON COLUMN INSCRIPCIONES.EST_MATRICULA IS 'MAtricula Estudiante';

CREATE SEQUENCE CONDICIONES_ESPECIALES_SEQ;

CREATE TRIGGER CONDICIONES_ESPECIALES_TRG 
BEFORE INSERT ON CONDICIONES_ESPECIALES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CONDICION IS NULL THEN
      SELECT CONDICIONES_ESPECIALES_SEQ.NEXTVAL INTO :NEW.ID_CONDICION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

DROP SEQUENCE CONDICIONES_ESPECIALES_SEQ;

CREATE SEQUENCE CONDICIONES_ESPECIALES_SEQ INCREMENT BY 1 START WITH 6 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

ALTER TABLE DETALLE_FACTURA 
DROP CONSTRAINT FK_FACT;

ALTER TABLE DETALLE_FACTURA 
RENAME CONSTRAINT DETALLE_FACTURA_MATERIALES_FK TO DET_FAC_MATERIALES_FK;

ALTER TABLE DETALLE_FACTURA 
RENAME CONSTRAINT DETALLE_FACTURA_TIPO_MATERIAL_FK TO DET_FAC_TIPO_MATERIAL_FK;

ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT FK_FACT FOREIGN KEY
(
  FACTURA_ID 
)
REFERENCES FACTURA
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE INSCRIPCIONES 
DROP CONSTRAINT INSCRIPCIONES_FACTURA_FK;

ALTER TABLE INSCRIPCIONES
ADD CONSTRAINT INSCRIPCIONES_FACTURA_FK FOREIGN KEY
(
  FACTURA_ID 
)
REFERENCES FACTURA
(
  ID 
)
ON DELETE CASCADE ENABLE;


ALTER TABLE FACTURA 
ADD (INSCRIPCION_ID NUMBER );

ALTER TABLE FACTURA
ADD CONSTRAINT FACTURA_FK1 FOREIGN KEY
(
  INSCRIPCION_ID 
)
REFERENCES INSCRIPCIONES
(
  ID 
)
ENABLE;

CREATE TABLE "JOB_LOG" 
(	"LOG_ID" NUMBER(9,0), 
"LOG_MESSAGE" VARCHAR2(1000 BYTE), 
"LOG_TIME" TIMESTAMP (6), 
 PRIMARY KEY ("LOG_ID")
);