--------------------------------------------------------
--  DDL for Table CONCEPTO_GRUPO
--------------------------------------------------------

  CREATE TABLE "JUPITER"."CONCEPTO_GRUPO" 
   (	"CG_CONCEPTO" NUMBER(10,0), 
	"CG_CONCEPTO_SUP" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JUPITER" ;
REM INSERTING into JUPITER.CONCEPTO_GRUPO
SET DEFINE OFF;
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('940','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('150','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('152','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('153','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('154','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('155','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('159','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('916','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('937','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('144','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('942','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('943','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('944','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('950','940');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('917','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('113','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('135','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('143','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('167','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('898','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('914','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('110','917');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('968','968');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('199','968');
Insert into JUPITER.CONCEPTO_GRUPO (CG_CONCEPTO,CG_CONCEPTO_SUP) values ('156','968');
--------------------------------------------------------
--  DDL for Index CONCEPTO_GRUPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUPITER"."CONCEPTO_GRUPO_PK" ON "JUPITER"."CONCEPTO_GRUPO" ("CG_CONCEPTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JUPITER" ;
--------------------------------------------------------
--  DDL for Trigger CONCEPTO_GRUPO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JUPITER"."CONCEPTO_GRUPO_TRG" 
BEFORE INSERT ON CONCEPTO_GRUPO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JUPITER"."CONCEPTO_GRUPO_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CONCEPTO_GRUPO
--------------------------------------------------------

  ALTER TABLE "JUPITER"."CONCEPTO_GRUPO" MODIFY ("CG_CONCEPTO" NOT NULL ENABLE);
  ALTER TABLE "JUPITER"."CONCEPTO_GRUPO" MODIFY ("CG_CONCEPTO_SUP" NOT NULL ENABLE);
  ALTER TABLE "JUPITER"."CONCEPTO_GRUPO" ADD CONSTRAINT "CONCEPTO_GRUPO_PK" PRIMARY KEY ("CG_CONCEPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JUPITER"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONCEPTO_GRUPO
--------------------------------------------------------

  ALTER TABLE "JUPITER"."CONCEPTO_GRUPO" ADD CONSTRAINT "CONCEPTO_GRUPO_FK1" FOREIGN KEY ("CG_CONCEPTO_SUP")
	  REFERENCES "JUPITER"."CONCEPTO_GRUPO" ("CG_CONCEPTO") ENABLE;
