--------------------------------------------------------
--  Constraints for Table FACTURA_DEPOSITO
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."FACTURA_DEPOSITO" MODIFY ("DEPOSITO_ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."FACTURA_DEPOSITO" MODIFY ("FACTURA_ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."FACTURA_DEPOSITO" ADD CONSTRAINT "FACTURA_DEPOSITO_PK" PRIMARY KEY ("FACTURA_ID", "DEPOSITO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSCRIPCIONES_BAK
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_BAK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_BAK" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_BAK" MODIFY ("EST_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_BAK" MODIFY ("SECCION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."DETALLE_FACTURA" MODIFY ("RENGLON" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."DETALLE_FACTURA" MODIFY ("MATERIALES_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."DETALLE_FACTURA" MODIFY ("FACTURA_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."DETALLE_FACTURA" ADD CONSTRAINT "DETALLE_FACTURA_PK" PRIMARY KEY ("RENGLON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_MATERIAL
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."TIPO_MATERIAL" MODIFY ("USA_SECCION" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."TIPO_MATERIAL" ADD CONSTRAINT "PK_TIPO_MATERIAL" PRIMARY KEY ("ABREV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPANIAS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."COMPANIAS" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."COMPANIAS" ADD CONSTRAINT "COMPANIAS_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRECIOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."PRECIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."PRECIOS" MODIFY ("TIPO_ITEM" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."PRECIOS" MODIFY ("PRECIO1" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."PRECIOS" ADD CONSTRAINT "PRECIOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_PROFESOR
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."TIPO_PROFESOR" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."TIPO_PROFESOR" ADD PRIMARY KEY ("ID_TIPO_PROF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EDIFICIOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."EDIFICIOS" MODIFY ("ID_EDIF" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."EDIFICIOS" ADD CONSTRAINT "EDIFICIOS_PK" PRIMARY KEY ("ID_EDIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIPLOMADOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."DIPLOMADOS" MODIFY ("ID_DIPLOMADO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."DIPLOMADOS" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."DIPLOMADOS" MODIFY ("HORAS" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."DIPLOMADOS" MODIFY ("COORDINADOR" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."DIPLOMADOS" MODIFY ("ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."DIPLOMADOS" ADD CONSTRAINT "DIPLOMADOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."DIPLOMADOS" ADD CONSTRAINT "DIPLOMADOS_UK1" UNIQUE ("ID_DIPLOMADO") DISABLE;
--------------------------------------------------------
--  Constraints for Table CONDICIONES_ESPECIALES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CONDICIONES_ESPECIALES" MODIFY ("ID_CONDICION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."CONDICIONES_ESPECIALES" ADD CONSTRAINT "CONDICIONES_ESPECIALES_PK" PRIMARY KEY ("ID_CONDICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MODALIDADES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."MODALIDADES" MODIFY ("ID_MODALIDAD" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."MODALIDADES" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."MODALIDADES" ADD CONSTRAINT "MODALIDADES_PK" PRIMARY KEY ("ID_MODALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."MODALIDADES" ADD CONSTRAINT "MODALIDAD_UK" UNIQUE ("DESCRIPCION") DISABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CLIENTES" MODIFY ("RIF" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CLIENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."CLIENTES" ADD CONSTRAINT "CLIENTES_UK1" UNIQUE ("RIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OCUPACIONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."OCUPACIONES" ADD CONSTRAINT "OCUPACIONES_PK" PRIMARY KEY ("ID_OCUPACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMA_PAGO
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."FORMA_PAGO" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."FORMA_PAGO" ADD CONSTRAINT "FORMA_PAGO_PK" PRIMARY KEY ("ID_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSCRIPCIONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" MODIFY ("EST_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" MODIFY ("SECCION_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" MODIFY ("ES_EXONERADO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" MODIFY ("PROG_ACADEMICO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" MODIFY ("ES_SUSPENDIDO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" ADD CONSTRAINT "INSCRIPCIONES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HORARIOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."HORARIOS" MODIFY ("ID_HORARIO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."HORARIOS" MODIFY ("MODALIDAD" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."HORARIOS" ADD CONSTRAINT "HORARIOS_PK" PRIMARY KEY ("ID_HORARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."FACTURA" MODIFY ("MONTO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."FACTURA" MODIFY ("ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."FACTURA" MODIFY ("CREADO_EL" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."FACTURA" MODIFY ("ESCREDITO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."FACTURA" ADD CONSTRAINT "PK_FACT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZONAS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."ZONAS" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."ZONAS" ADD CONSTRAINT "ZONAS_PK" PRIMARY KEY ("ID_ZONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIALES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."MATERIALES" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."MATERIALES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."MATERIALES" MODIFY ("IVA_EXENTO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."MATERIALES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."MATERIALES" ADD CONSTRAINT "MATERIALES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALENDARIOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CALENDARIOS" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."CALENDARIOS" MODIFY ("ACTIVO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."CALENDARIOS" MODIFY ("TIPO_CAL" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CALENDARIOS" ADD CONSTRAINT "CALENDARIOS_PK" PRIMARY KEY ("ID_CALENDARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."PROFESOR" MODIFY ("NACIONALIDAD" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."PROFESOR" MODIFY ("NOMBRE" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."PROFESOR" ADD CONSTRAINT "PROFESOR_PK" PRIMARY KEY ("CEDULA_PROF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROGRAMA_ACADEMICO
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."PROGRAMA_ACADEMICO" ADD CONSTRAINT "PROGRAMA_ACADEMICO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."PROGRAMA_ACADEMICO" ADD CONSTRAINT "PROGRAMA_ACADEMICO_CHK1" CHECK (activo in ('S','N')) DISABLE;
--------------------------------------------------------
--  Constraints for Table CONFIGURACION
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CONFIGURACION" MODIFY ("ULT_FACTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METODOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."METODOS" ADD CONSTRAINT "PK_METODO" PRIMARY KEY ("ID_METODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."DEPT" ADD PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPOSITO
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."DEPOSITO" MODIFY ("REFERENCIA" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."DEPOSITO" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."DEPOSITO" MODIFY ("ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."DEPOSITO" ADD CONSTRAINT "PK_DEPOSITO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."DEPOSITO" ADD CONSTRAINT "DEPOSITO_UK" UNIQUE ("REFERENCIA", "ID_BANCO", "FORMA_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."USUARIOS" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."USUARIOS" MODIFY ("BLOQUEADO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."USUARIOS" MODIFY ("CREADO_EL" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."USUARIOS" ADD CONSTRAINT "USUARIOS_UK1" UNIQUE ("NOMBRE_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TE_TEMPLATES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."TE_TEMPLATES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."TE_TEMPLATES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."TE_TEMPLATES" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."TE_TEMPLATES" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."TE_TEMPLATES" ADD CONSTRAINT "TE_TEMPLATES_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANCOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."BANCOS" MODIFY ("NOMBRE" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."BANCOS" ADD CONSTRAINT "BANCOS_PK" PRIMARY KEY ("ID_BANCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."EMP" ADD PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSCRIPCION_FACTURA
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."INSCRIPCION_FACTURA" MODIFY ("INSCRIPCION_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCION_FACTURA" MODIFY ("FACTURA_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCION_FACTURA" ADD CONSTRAINT "INSCRIP_FAC_PK" PRIMARY KEY ("INSCRIPCION_ID", "FACTURA_ID")
  USING INDEX (CREATE UNIQUE INDEX "FUNDAUC"."INSCRIPCION_FACTURA_PK" ON "FUNDAUC"."INSCRIPCION_FACTURA" ("INSCRIPCION_ID", "FACTURA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA_BAK
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."FACTURA_BAK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."ESTUDIANTE" MODIFY ("NACIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" MODIFY ("ID_TIPO_EST" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" ADD CONSTRAINT "PK_ESTUDIANTE" PRIMARY KEY ("MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 720896 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."SALONES" MODIFY ("CAPACIDAD" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."SALONES" ADD CONSTRAINT "PK_SALON" PRIMARY KEY ("ID_SALON", "EDIFICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOJA_VIDA_EST_BK
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST_BK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST_BK" ADD CONSTRAINT "HOJA_VIDA_BK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECCIONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."SECCIONES" MODIFY ("ID_METODO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."SECCIONES" MODIFY ("MODALIDAD" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."SECCIONES" MODIFY ("ID_HORARIO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."SECCIONES" MODIFY ("ID_CALENDARIO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."SECCIONES" MODIFY ("ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."SECCIONES" ADD CONSTRAINT "SECCIONES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."SECCIONES" ADD CONSTRAINT "SECCIONES_UK1" UNIQUE ("ID_SECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSTANCIAS_SECCIONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."INSTANCIAS_SECCIONES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSTANCIAS_SECCIONES" ADD CONSTRAINT "INSTANCIAS_SECCIONES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."INSTANCIAS_SECCIONES" MODIFY ("F_INICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOB_LOG
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."JOB_LOG" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOJA_VIDA_EST
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST" ADD CONSTRAINT "CC_JSON_METADATA" CHECK (METADATA is JSON) ENABLE;
  ALTER TABLE "FUNDAUC"."HOJA_VIDA_EST" ADD CONSTRAINT "HOJA_VIDA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSCRIPCIONES_HIS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_HIS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_HIS" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_HIS" MODIFY ("EST_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_HIS" MODIFY ("SECCION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSCRIPCIONES_RESP
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."INSCRIPCIONES_RESP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CIUDADES" ADD CONSTRAINT "CIUDADES_PK" PRIMARY KEY ("ID_CIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."TIPO_ESTUDIANTE" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."TIPO_ESTUDIANTE" ADD CONSTRAINT "TIPO_ESTUDIANTE_PK" PRIMARY KEY ("ID_TIPO_EST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECCIONES_BAK
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."SECCIONES_BAK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."ESTADOS" ADD CONSTRAINT "ESTADOS_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTAXCOB
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CTAXCOB" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CTAXCOB" MODIFY ("CLIENTE_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CTAXCOB" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CTAXCOB" MODIFY ("CREDITO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CTAXCOB" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "FUNDAUC"."CTAXCOB" ADD CONSTRAINT "CTAXCOB_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALENDARIOS_DETALLE
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" MODIFY ("ID_CALENDARIO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" MODIFY ("PERIODO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" MODIFY ("MODALIDAD" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" MODIFY ("ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" ADD CONSTRAINT "CALENDARIOS_DETALLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" ADD CONSTRAINT "CK_PER_ACTIVO" CHECK ( periodo_activo IN (
        'N',
        'S'
    ) ) DISABLE;
--------------------------------------------------------
--  Constraints for Table EVENTOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."EVENTOS" MODIFY ("DESCRIPCION" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."EVENTOS" ADD CONSTRAINT "EVENTOS_PK" PRIMARY KEY ("ID_EVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COHORTES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."COHORTES" MODIFY ("ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."COHORTES" MODIFY ("TIPO_DIPLO" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."COHORTES" MODIFY ("DIPLOMADO_ID" NOT NULL DISABLE);
  ALTER TABLE "FUNDAUC"."COHORTES" ADD CONSTRAINT "COHORTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC"  ENABLE;
  ALTER TABLE "FUNDAUC"."COHORTES" ADD CONSTRAINT "COHORTES_UK1" UNIQUE ("CODIGO") DISABLE;
