--------------------------------------------------------
--  DDL for Index SYS_C0018511
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018511" ON "FUNDAUC"."BANCOS" ("ID_BANCO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018513
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018513" ON "FUNDAUC"."CALENDARIOS" ("ID_CALENDARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index CALENDARIOS_DETALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."CALENDARIOS_DETALLE_PK" ON "FUNDAUC"."CALENDARIOS_DETALLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018514
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018514" ON "FUNDAUC"."CIUDADES" ("ID_CIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."CLIENTES_PK" ON "FUNDAUC"."CLIENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018547
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018547" ON "FUNDAUC"."CLIENTES" ("RIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index COHORTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."COHORTES_PK" ON "FUNDAUC"."COHORTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018522
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018522" ON "FUNDAUC"."COMPANIAS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index CONDICIONES_ESPECIALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."CONDICIONES_ESPECIALES_PK" ON "FUNDAUC"."CONDICIONES_ESPECIALES" ("ID_CONDICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index CTAXCOB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."CTAXCOB_PK" ON "FUNDAUC"."CTAXCOB" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index PK_DEPOSITO
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."PK_DEPOSITO" ON "FUNDAUC"."DEPOSITO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index DEPOSITO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."DEPOSITO_UK" ON "FUNDAUC"."DEPOSITO" ("REFERENCIA", "ID_BANCO", "FORMA_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018532
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018532" ON "FUNDAUC"."DETALLE_FACTURA" ("RENGLON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index DIPLOMADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."DIPLOMADOS_PK" ON "FUNDAUC"."DIPLOMADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index EDIFICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."EDIFICIOS_PK" ON "FUNDAUC"."EDIFICIOS" ("ID_EDIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018552
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018552" ON "FUNDAUC"."ESTADOS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index PK_ESTUDIANTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."PK_ESTUDIANTE" ON "FUNDAUC"."ESTUDIANTE" ("MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 720896 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018558
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018558" ON "FUNDAUC"."EVENTOS" ("ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index PK_FACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."PK_FACT" ON "FUNDAUC"."FACTURA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index FACTURA_DEPOSITO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."FACTURA_DEPOSITO_PK" ON "FUNDAUC"."FACTURA_DEPOSITO" ("FACTURA_ID", "DEPOSITO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018578
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018578" ON "FUNDAUC"."FORMA_PAGO" ("ID_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index HORARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."HORARIOS_PK" ON "FUNDAUC"."HORARIOS" ("ID_HORARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index INSCRIPCIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."INSCRIPCIONES_PK" ON "FUNDAUC"."INSCRIPCIONES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index INSCRIPCION_FACTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."INSCRIPCION_FACTURA_PK" ON "FUNDAUC"."INSCRIPCION_FACTURA" ("INSCRIPCION_ID", "FACTURA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index MATERIALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."MATERIALES_PK" ON "FUNDAUC"."MATERIALES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index PK_METODO
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."PK_METODO" ON "FUNDAUC"."METODOS" ("ID_METODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index MODALIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."MODALIDADES_PK" ON "FUNDAUC"."MODALIDADES" ("ID_MODALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018591
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018591" ON "FUNDAUC"."OCUPACIONES" ("ID_OCUPACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index PRECIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."PRECIOS_PK" ON "FUNDAUC"."PRECIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018599
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018599" ON "FUNDAUC"."PROFESOR" ("CEDULA_PROF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018602
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018602" ON "FUNDAUC"."PROGRAMA_ACADEMICO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018603
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018603" ON "FUNDAUC"."ROLES" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index PK_SALON
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."PK_SALON" ON "FUNDAUC"."SALONES" ("ID_SALON", "EDIFICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SECCIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SECCIONES_PK" ON "FUNDAUC"."SECCIONES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SECCIONES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SECCIONES_UK1" ON "FUNDAUC"."SECCIONES" ("ID_SECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018611
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018611" ON "FUNDAUC"."TIPO_ESTUDIANTE" ("ID_TIPO_EST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_MATERIAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."PK_TIPO_MATERIAL" ON "FUNDAUC"."TIPO_MATERIAL" ("ABREV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index TIPO_PROF_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."TIPO_PROF_UK" ON "FUNDAUC"."TIPO_PROFESOR" ("ID_TIPO_PROF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018616
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018616" ON "FUNDAUC"."USUARIOS" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."USUARIOS_UK1" ON "FUNDAUC"."USUARIOS" ("NOMBRE_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018618
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."SYS_C0018618" ON "FUNDAUC"."ZONAS" ("ID_ZONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index HOJA_VIDA_BK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."HOJA_VIDA_BK_PK" ON "FUNDAUC"."HOJA_VIDA_EST_BK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index HOJA_VIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."HOJA_VIDA_PK" ON "FUNDAUC"."HOJA_VIDA_EST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index TE_TEMPLATES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."TE_TEMPLATES_PK" ON "FUNDAUC"."TE_TEMPLATES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index INSTANCIAS_SECCIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."INSTANCIAS_SECCIONES_PK" ON "FUNDAUC"."INSTANCIAS_SECCIONES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index INSCRIPCIONES_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."INSCRIPCIONES_UK" ON "FUNDAUC"."INSCRIPCIONES" (TRUNC("FECHA_INS"), "EST_MATRICULA", "SECCION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index MATERIALES_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."MATERIALES_UK" ON "FUNDAUC"."MATERIALES" ("ID_MAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index IDX_CEDULA_EST_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."IDX_CEDULA_EST_UN" ON "FUNDAUC"."ESTUDIANTE" ("CEDULA_EST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 720896 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index DIPLOMADOS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."DIPLOMADOS_UK1" ON "FUNDAUC"."DIPLOMADOS" ("ID_DIPLOMADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index MODALIDAD_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."MODALIDAD_UK" ON "FUNDAUC"."MODALIDADES" ("DESCRIPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index CALENDARIOS_DETALLE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."CALENDARIOS_DETALLE_IDX" ON "FUNDAUC"."CALENDARIOS_DETALLE" ("ID_CALENDARIO", "PERIODO", "MODALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index COHORTES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."COHORTES_UK1" ON "FUNDAUC"."COHORTES" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Index I_HORARIO_H
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNDAUC"."I_HORARIO_H" ON "FUNDAUC"."HORARIOS" ("MODALIDAD", TO_CHAR("HORA",'HH:MI AM'), TO_CHAR("HORA_FIN",'HH:MI AM')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
