--------------------------------------------------------
--  Ref Constraints for Table CALENDARIOS_DETALLE
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" ADD CONSTRAINT "CALENDARIOS_DET_MOD_FK" FOREIGN KEY ("MODALIDAD")
	  REFERENCES "FUNDAUC"."MODALIDADES" ("ID_MODALIDAD") ENABLE;
  ALTER TABLE "FUNDAUC"."CALENDARIOS_DETALLE" ADD CONSTRAINT "CALENDARIOS_DET_CAL_FK" FOREIGN KEY ("ID_CALENDARIO")
	  REFERENCES "FUNDAUC"."CALENDARIOS" ("ID_CALENDARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."CIUDADES" ADD CONSTRAINT "CIUD_EST_FK" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "FUNDAUC"."ESTADOS" ("ID_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COHORTES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."COHORTES" ADD CONSTRAINT "COHORTES_DIPLOMADOS_FK" FOREIGN KEY ("DIPLOMADO_ID")
	  REFERENCES "FUNDAUC"."DIPLOMADOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."DETALLE_FACTURA" ADD CONSTRAINT "DET_FAC_MATERIALES_FK" FOREIGN KEY ("MATERIALES_ID")
	  REFERENCES "FUNDAUC"."MATERIALES" ("ID") DISABLE;
  ALTER TABLE "FUNDAUC"."DETALLE_FACTURA" ADD CONSTRAINT "FK_FACT" FOREIGN KEY ("FACTURA_ID")
	  REFERENCES "FUNDAUC"."FACTURA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FUNDAUC"."DETALLE_FACTURA" ADD CONSTRAINT "DET_FAC_TIPO_MAT_FK1" FOREIGN KEY ("TIPO_ITEM")
	  REFERENCES "FUNDAUC"."TIPO_MATERIAL" ("ABREV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."EMP" ADD FOREIGN KEY ("DEPTNO")
	  REFERENCES "FUNDAUC"."DEPT" ("DEPTNO") ENABLE;
  ALTER TABLE "FUNDAUC"."EMP" ADD FOREIGN KEY ("MGR")
	  REFERENCES "FUNDAUC"."EMP" ("EMPNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_OCUPACIONES_FK" FOREIGN KEY ("PROFESION")
	  REFERENCES "FUNDAUC"."OCUPACIONES" ("ID_OCUPACION") ENABLE;
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_CIUDADES_FK" FOREIGN KEY ("CIUDAD")
	  REFERENCES "FUNDAUC"."CIUDADES" ("ID_CIUDAD") ENABLE;
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_COMPANIAS_FK" FOREIGN KEY ("SEDE")
	  REFERENCES "FUNDAUC"."COMPANIAS" ("CODIGO") ENABLE;
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_ESTADOS_FK" FOREIGN KEY ("ESTADO")
	  REFERENCES "FUNDAUC"."ESTADOS" ("ID_ESTADO") ENABLE;
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" ADD CONSTRAINT "EST_TP_EST_FK" FOREIGN KEY ("ID_TIPO_EST")
	  REFERENCES "FUNDAUC"."TIPO_ESTUDIANTE" ("ID_TIPO_EST") ENABLE;
  ALTER TABLE "FUNDAUC"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_ZONAS_FK" FOREIGN KEY ("ZONA")
	  REFERENCES "FUNDAUC"."ZONAS" ("ID_ZONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."FACTURA" ADD CONSTRAINT "FACTURA_COMPANIAS_FK" FOREIGN KEY ("PROGRAMA")
	  REFERENCES "FUNDAUC"."COMPANIAS" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURA_DEPOSITO
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."FACTURA_DEPOSITO" ADD CONSTRAINT "FACTURA_DEPOSITO_DEPOSITO_FK" FOREIGN KEY ("DEPOSITO_ID")
	  REFERENCES "FUNDAUC"."DEPOSITO" ("ID") ENABLE;
  ALTER TABLE "FUNDAUC"."FACTURA_DEPOSITO" ADD CONSTRAINT "FACTURA_DEPOSITO_FACTURA_FK" FOREIGN KEY ("FACTURA_ID")
	  REFERENCES "FUNDAUC"."FACTURA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSCRIPCIONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" ADD CONSTRAINT "INSCRIPCIONES_SECCIONES_FK" FOREIGN KEY ("SECCION_ID")
	  REFERENCES "FUNDAUC"."SECCIONES" ("ID") ENABLE;
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" ADD CONSTRAINT "INSCRIPCIONES_FK1" FOREIGN KEY ("COHORTE_ID")
	  REFERENCES "FUNDAUC"."COHORTES" ("ID") ENABLE;
  ALTER TABLE "FUNDAUC"."INSCRIPCIONES" ADD CONSTRAINT "INSCRIPCIONES_ESTUDIANTE_FK" FOREIGN KEY ("EST_MATRICULA")
	  REFERENCES "FUNDAUC"."ESTUDIANTE" ("MATRICULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIALES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."MATERIALES" ADD CONSTRAINT "MATERIALES_SECCIONES_FK" FOREIGN KEY ("SECCION_ID")
	  REFERENCES "FUNDAUC"."SECCIONES" ("ID") ENABLE;
  ALTER TABLE "FUNDAUC"."MATERIALES" ADD CONSTRAINT "MATERIALES_COHORTES_FK" FOREIGN KEY ("COHORTE_ID")
	  REFERENCES "FUNDAUC"."COHORTES" ("ID") ENABLE;
  ALTER TABLE "FUNDAUC"."MATERIALES" ADD CONSTRAINT "MATERIALES_TIPO_MATERIAL_FK" FOREIGN KEY ("TIPO")
	  REFERENCES "FUNDAUC"."TIPO_MATERIAL" ("ABREV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRECIOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."PRECIOS" ADD CONSTRAINT "PRECIOS_FK1" FOREIGN KEY ("ID")
	  REFERENCES "FUNDAUC"."MATERIALES" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."SALONES" ADD CONSTRAINT "SALONES_EDIFICIOS_FK" FOREIGN KEY ("EDIFICIO")
	  REFERENCES "FUNDAUC"."EDIFICIOS" ("ID_EDIF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECCIONES
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."SECCIONES" ADD CONSTRAINT "SECCIONES_METODOS_FK" FOREIGN KEY ("ID_METODO")
	  REFERENCES "FUNDAUC"."METODOS" ("ID_METODO") ENABLE;
  ALTER TABLE "FUNDAUC"."SECCIONES" ADD CONSTRAINT "SECCIONES_MODALIDADES_FK" FOREIGN KEY ("MODALIDAD")
	  REFERENCES "FUNDAUC"."MODALIDADES" ("ID_MODALIDAD") ENABLE;
  ALTER TABLE "FUNDAUC"."SECCIONES" ADD CONSTRAINT "SECCIONES_PROFESOR_FK" FOREIGN KEY ("CEDULA_PROF")
	  REFERENCES "FUNDAUC"."PROFESOR" ("CEDULA_PROF") ENABLE;
  ALTER TABLE "FUNDAUC"."SECCIONES" ADD CONSTRAINT "SECCIONES_SALONES_FK" FOREIGN KEY ("ID_SALON", "ID_EDIF")
	  REFERENCES "FUNDAUC"."SALONES" ("ID_SALON", "EDIFICIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."USUARIOS" ADD CONSTRAINT "USR_ROL_FK" FOREIGN KEY ("ID_ROL")
	  REFERENCES "FUNDAUC"."ROLES" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZONAS
--------------------------------------------------------

  ALTER TABLE "FUNDAUC"."ZONAS" ADD CONSTRAINT "FK_ZONAS" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "FUNDAUC"."CIUDADES" ("ID_CIUDAD") ENABLE;
