--------------------------------------------------------
--  DDL for Table BANCOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."BANCOS" 
   (	"ID_BANCO" NUMBER(2,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE), 
	"DEBITO" CHAR(1 BYTE), 
	"DEPOSITO" CHAR(1 BYTE), 
	"CREDITO" CHAR(1 BYTE), 
	"CTA" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."BANCOS"."ID_BANCO" IS 'ID_BANCO';
   COMMENT ON COLUMN "FUNDAUC"."BANCOS"."NOMBRE" IS 'NOMBRE';
   COMMENT ON COLUMN "FUNDAUC"."BANCOS"."CIUDAD" IS 'CIUDAD';
   COMMENT ON COLUMN "FUNDAUC"."BANCOS"."DEBITO" IS 'DEBITO';
   COMMENT ON COLUMN "FUNDAUC"."BANCOS"."DEPOSITO" IS 'DEPOSITO';
   COMMENT ON COLUMN "FUNDAUC"."BANCOS"."CREDITO" IS 'CREDITO';
   COMMENT ON COLUMN "FUNDAUC"."BANCOS"."CTA" IS 'CTA';
   COMMENT ON TABLE "FUNDAUC"."BANCOS"  IS 'BANCOS';
--------------------------------------------------------
--  DDL for Table CALENDARIOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CALENDARIOS" 
   (	"ID_CALENDARIO" NUMBER(3,0), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ACTIVO" CHAR(1 BYTE) DEFAULT 'S', 
	"TIPO_CAL" CHAR(1 BYTE) DEFAULT 'I'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS"."ID_CALENDARIO" IS 'ID_CALENDARIO';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS"."ACTIVO" IS 'ACTIVO SI O NO';
   COMMENT ON TABLE "FUNDAUC"."CALENDARIOS"  IS 'CALENDARIOS';
--------------------------------------------------------
--  DDL for Table CALENDARIOS_DETALLE
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CALENDARIOS_DETALLE" 
   (	"ID_CALENDARIO" NUMBER(3,0), 
	"PERIODO" NUMBER(6,0), 
	"FECHA_INI" DATE, 
	"FECHA_FIN" DATE, 
	"MODALIDAD" NUMBER(2,0), 
	"PERIODO_ACTIVO" CHAR(1 BYTE) DEFAULT 'S', 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS_DETALLE"."ID_CALENDARIO" IS 'ID_CALENDARIO';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS_DETALLE"."PERIODO" IS 'PERIODO';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS_DETALLE"."FECHA_INI" IS 'FECHA_INI';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS_DETALLE"."FECHA_FIN" IS 'FECHA_FIN';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS_DETALLE"."MODALIDAD" IS 'MODALIDAD';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS_DETALLE"."PERIODO_ACTIVO" IS 'Si el Periodo esta Activo o no';
   COMMENT ON COLUMN "FUNDAUC"."CALENDARIOS_DETALLE"."ID" IS 'Identificador Unico de Calendario';
   COMMENT ON TABLE "FUNDAUC"."CALENDARIOS_DETALLE"  IS 'CALENDARIOS_DETALLE';
--------------------------------------------------------
--  DDL for Table CIUDADES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CIUDADES" 
   (	"ID_CIUDAD" NUMBER(10,0), 
	"ID_ESTADO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"ES_CAPITAL" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."CIUDADES"."ID_CIUDAD" IS 'ID_CIUDAD';
   COMMENT ON COLUMN "FUNDAUC"."CIUDADES"."ID_ESTADO" IS 'ID_ESTADO';
   COMMENT ON COLUMN "FUNDAUC"."CIUDADES"."NOMBRE" IS 'NOMBRE';
   COMMENT ON TABLE "FUNDAUC"."CIUDADES"  IS 'CIUDADES';
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CLIENTES" 
   (	"RIF" VARCHAR2(16 BYTE), 
	"RAZON" VARCHAR2(60 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(14 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."CLIENTES"."RIF" IS 'RIF';
   COMMENT ON COLUMN "FUNDAUC"."CLIENTES"."RAZON" IS 'RAZON';
   COMMENT ON COLUMN "FUNDAUC"."CLIENTES"."DIRECCION" IS 'DIRECCION';
   COMMENT ON COLUMN "FUNDAUC"."CLIENTES"."TELEFONO" IS 'TELEFONO';
   COMMENT ON TABLE "FUNDAUC"."CLIENTES"  IS 'EMPRESAS';
--------------------------------------------------------
--  DDL for Table CLIENTES_BAK
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CLIENTES_BAK" 
   (	"RIF" VARCHAR2(16 BYTE), 
	"RAZON" VARCHAR2(60 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table COHORTES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."COHORTES" 
   (	"CODIGO" VARCHAR2(20 BYTE), 
	"ID_HORARIO" NUMBER, 
	"ID_MODALIDAD" NUMBER(2,0), 
	"COHORTE" NUMBER(3,0), 
	"CUPO" NUMBER(5,0), 
	"COSTO" NUMBER(14,2), 
	"INICIAL" NUMBER(14,2), 
	"COSTO_CUOTA" NUMBER(14,2), 
	"CUOTAS" NUMBER(3,0), 
	"STATUS" CHAR(1 BYTE), 
	"ID_CIUDAD" NUMBER, 
	"ID" NUMBER, 
	"TIPO_DIPLO" VARCHAR2(15 BYTE), 
	"CREADO_POR" VARCHAR2(255 BYTE), 
	"CREADO_EL" DATE, 
	"MODIFICADO_POR" VARCHAR2(255 BYTE), 
	"MODIFICADO_EL" DATE, 
	"DIPLOMADO_ID" NUMBER, 
	"PERIODO" NUMBER, 
	"ID_CALENDARIO" NUMBER, 
	"NIVEL" NUMBER, 
	"ID_METODO" NUMBER, 
	"EMPRESA" NUMBER, 
	"FACILITADOR" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."CODIGO" IS 'CODIGO';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."ID_HORARIO" IS 'ID_HORARIO';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."ID_MODALIDAD" IS 'ID_MODALIDAD';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."COHORTE" IS 'COHORTE';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."CUPO" IS 'CANT_ACTUAL';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."COSTO" IS 'COSTO';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."INICIAL" IS 'INICIAL';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."COSTO_CUOTA" IS 'COSTO_CUOTA';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."CUOTAS" IS 'CUOTAS';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."ID_CIUDAD" IS 'CIUDAD';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."ID" IS 'Identificador unico de Cohorte';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."TIPO_DIPLO" IS 'Tipo de diplomado: Ej ADMINISTRADO, CERTIFICACION';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."CREADO_POR" IS 'usuario quien crea la seccion';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."CREADO_EL" IS 'Fecha de Creacion';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."MODIFICADO_POR" IS 'usuario quien modifica la seccion';
   COMMENT ON COLUMN "FUNDAUC"."COHORTES"."MODIFICADO_EL" IS 'Fecha de Modificacion';
   COMMENT ON TABLE "FUNDAUC"."COHORTES"  IS 'COHORTES';
--------------------------------------------------------
--  DDL for Table COMPANIAS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."COMPANIAS" 
   (	"CODIGO" VARCHAR2(3 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"ID" NUMBER(2,0), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DIRECTOR" VARCHAR2(60 BYTE), 
	"CIUDAD" VARCHAR2(30 BYTE), 
	"SERIE" VARCHAR2(10 BYTE), 
	"ACTIVA" CHAR(1 BYTE) DEFAULT 'S', 
	"IVA" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."CODIGO" IS 'CODIGO';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."ID" IS 'ID';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."DIRECCION" IS 'DIRECCION';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."TELEFONO" IS 'TELEFONO';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."EMAIL" IS 'EMAIL';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."DIRECTOR" IS 'DIRECTOR';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."CIUDAD" IS 'CIUDAD';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."SERIE" IS 'SERIE';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."ACTIVA" IS 'ACTIVA';
   COMMENT ON COLUMN "FUNDAUC"."COMPANIAS"."IVA" IS 'IVA';
   COMMENT ON TABLE "FUNDAUC"."COMPANIAS"  IS 'COMPANIAS';
--------------------------------------------------------
--  DDL for Table CONDICIONES_ESPECIALES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CONDICIONES_ESPECIALES" 
   (	"ID_CONDICION" VARCHAR2(2 BYTE), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"DESCUENTO" VARCHAR2(10 BYTE), 
	"PORCENTAJE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."CONDICIONES_ESPECIALES"."ID_CONDICION" IS 'ID_CONDICION';
   COMMENT ON COLUMN "FUNDAUC"."CONDICIONES_ESPECIALES"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."CONDICIONES_ESPECIALES"."DESCUENTO" IS 'DESCUENTO';
   COMMENT ON COLUMN "FUNDAUC"."CONDICIONES_ESPECIALES"."PORCENTAJE" IS 'PORCENTAJE DE DESCUENTO';
   COMMENT ON TABLE "FUNDAUC"."CONDICIONES_ESPECIALES"  IS 'CONDICIONES_ESPECIALES';
--------------------------------------------------------
--  DDL for Table CONFIGURACION
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CONFIGURACION" 
   (	"ULT_FACTURA" NUMBER, 
	"PORC_TARJ_DEB" NUMBER(10,5), 
	"PORC_TARJ_CRE" NUMBER(10,5), 
	"TASA_IVA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."CONFIGURACION"."ULT_FACTURA" IS 'Ultimo Correlativo de Factura automatica';
   COMMENT ON COLUMN "FUNDAUC"."CONFIGURACION"."PORC_TARJ_DEB" IS 'Porcentaje Comision tarjeta de Debito';
   COMMENT ON COLUMN "FUNDAUC"."CONFIGURACION"."PORC_TARJ_CRE" IS 'Porcentaje comision Tarjeta de Credito';
--------------------------------------------------------
--  DDL for Table CTAXCOB
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."CTAXCOB" 
   (	"ID" NUMBER, 
	"CLIENTE_ID" NUMBER, 
	"FECHA" DATE, 
	"FACTURA_ID" NUMBER, 
	"DEPOSITO_ID" NUMBER, 
	"CREDITO" VARCHAR2(2 BYTE), 
	"MONTO" NUMBER(12,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table DEPOSITO
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."DEPOSITO" 
   (	"REFERENCIA" VARCHAR2(20 BYTE), 
	"FECHA_EMI" DATE, 
	"ID_BANCO" NUMBER(2,0), 
	"MONTO" NUMBER(14,2), 
	"SEDE" VARCHAR2(5 BYTE), 
	"USUARIO" VARCHAR2(50 BYTE) DEFAULT coalesce(sys_context('APEX$SESSION', 'app_user'), regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*'), sys_context('userenv', 'session_user')), 
	"STATUS" VARCHAR2(1 BYTE), 
	"FORMA_PAGO" NUMBER(2,0), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."REFERENCIA" IS 'REFERENCIA';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."FECHA_EMI" IS 'FECHA_EMI';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."ID_BANCO" IS 'ID_BANCO';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."MONTO" IS 'MONTO';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."SEDE" IS 'CIA';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."USUARIO" IS 'USUARIO';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."FORMA_PAGO" IS 'FORMA_PAGO';
   COMMENT ON COLUMN "FUNDAUC"."DEPOSITO"."ID" IS 'Identificador Unido del Pago de factura';
   COMMENT ON TABLE "FUNDAUC"."DEPOSITO"  IS 'DEPOSITO';
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table DETALLE_FACTURA
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."DETALLE_FACTURA" 
   (	"RENGLON" NUMBER(12,0), 
	"TIPO_ITEM" VARCHAR2(3 BYTE), 
	"ITEM" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"CANTIDAD" NUMBER(8,2), 
	"P_UNIDAD" NUMBER(14,2), 
	"BS_DESCUENTO" NUMBER(14,2), 
	"SUBTOTAL" NUMBER(14,2), 
	"MATERIALES_ID" NUMBER, 
	"FACTURA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 851968 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."RENGLON" IS 'RENGLON';
   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."TIPO_ITEM" IS 'TIPO_ITEM';
   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."CANTIDAD" IS 'CANTIDAD';
   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."P_UNIDAD" IS 'P_UNIDAD';
   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."BS_DESCUENTO" IS 'BS_DESCUENTO';
   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."SUBTOTAL" IS 'SUBTOTAL';
   COMMENT ON COLUMN "FUNDAUC"."DETALLE_FACTURA"."FACTURA_ID" IS 'id de la factura';
   COMMENT ON TABLE "FUNDAUC"."DETALLE_FACTURA"  IS 'DETALLE_FACTURA';
--------------------------------------------------------
--  DDL for Table DIPLOMADOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."DIPLOMADOS" 
   (	"ID_DIPLOMADO" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"HORAS" NUMBER(3,0), 
	"COORDINADOR" VARCHAR2(100 BYTE), 
	"MODULOS" NUMBER(3,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"CLASE_DOC" NUMBER(3,0), 
	"MINIMO" NUMBER(3,0), 
	"MAXIMO" NUMBER(3,0), 
	"COD_CONTABLE" VARCHAR2(15 BYTE), 
	"COD_DESCUENTO" VARCHAR2(15 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."ID_DIPLOMADO" IS 'ID_DIPLOMADO';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."HORAS" IS 'HORAS';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."COORDINADOR" IS 'COORDINADOR';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."MODULOS" IS 'MODULOS';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."CLASE_DOC" IS 'CLASE_DOC';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."MINIMO" IS 'MINIMO';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."MAXIMO" IS 'MAXIMO';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."COD_CONTABLE" IS 'COD_CONTABLE';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."COD_DESCUENTO" IS 'COD_DESCUENTO';
   COMMENT ON COLUMN "FUNDAUC"."DIPLOMADOS"."ID" IS 'Identificador unico de diplomado';
   COMMENT ON TABLE "FUNDAUC"."DIPLOMADOS"  IS 'DIPLOMADOS';
--------------------------------------------------------
--  DDL for Table EDIFICIOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."EDIFICIOS" 
   (	"ID_EDIF" NUMBER(3,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."EDIFICIOS"."ID_EDIF" IS 'ID_EDIF';
   COMMENT ON COLUMN "FUNDAUC"."EDIFICIOS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON TABLE "FUNDAUC"."EDIFICIOS"  IS 'EDIFICIOS';
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."EMP" 
   (	"EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(9 BYTE), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table ESTADOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."ESTADOS" 
   (	"ID_ESTADO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."ESTADOS"."ID_ESTADO" IS 'ID_ESTADO';
   COMMENT ON COLUMN "FUNDAUC"."ESTADOS"."NOMBRE" IS 'NOMBRE';
   COMMENT ON TABLE "FUNDAUC"."ESTADOS"  IS 'ESTADOS';
--------------------------------------------------------
--  DDL for Table ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."ESTUDIANTE" 
   (	"CEDULA_EST" NUMBER(10,0), 
	"NACIONALIDAD" CHAR(1 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELF_HAB" VARCHAR2(14 BYTE), 
	"TELF_CEL" VARCHAR2(14 BYTE), 
	"CIUDAD" NUMBER(10,0), 
	"ESTADO" NUMBER(10,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"EDO_CIVIL" VARCHAR2(20 BYTE), 
	"GRADO_INS" VARCHAR2(20 BYTE), 
	"PROFESION" NUMBER, 
	"FECHA_NAC" DATE, 
	"STATUS" VARCHAR2(2 BYTE), 
	"ID_TIPO_EST" VARCHAR2(1 BYTE), 
	"RIF" VARCHAR2(16 BYTE), 
	"MATRICULA" NUMBER(10,0), 
	"SEDE" VARCHAR2(3 BYTE), 
	"CONDICION_ESPECIAL" VARCHAR2(2 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"ZONA" NUMBER, 
	"CEDULA_REP" VARCHAR2(16 BYTE), 
	"DIRECCION" VARCHAR2(500 BYTE), 
	"CREADO_POR" VARCHAR2(30 BYTE) DEFAULT coalesce(sys_context('APEX$SESSION', 'app_user'), regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*'), sys_context('userenv', 'session_user')), 
	"CREADO_EL" DATE DEFAULT SYSDATE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"MODIFICADO_EL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."CEDULA_EST" IS 'CEDULA_EST';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."NACIONALIDAD" IS 'NACIONALIDAD';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."NOMBRE" IS 'NOMBRE';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."TELF_HAB" IS 'TELF_HAB';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."TELF_CEL" IS 'TELF_CEL';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."CIUDAD" IS 'CIUDAD';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."ESTADO" IS 'ESTADO';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."EMAIL" IS 'EMAIL';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."SEXO" IS 'SEXO';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."EDO_CIVIL" IS 'EDO_CIVIL';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."GRADO_INS" IS 'GRADO_INS';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."PROFESION" IS 'PROFESION';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."FECHA_NAC" IS 'FECHA_NAC';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."ID_TIPO_EST" IS 'ID_TIPO_EST';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."RIF" IS 'RIF';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."MATRICULA" IS 'MATRICULA';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."SEDE" IS 'SEDE';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."CONDICION_ESPECIAL" IS 'CONDICION_ESPECIAL';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."APELLIDO" IS 'APELLIDO';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."ZONA" IS 'ZONA';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."CEDULA_REP" IS 'CEDULA_REP';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."DIRECCION" IS 'DIRECCION';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."CREADO_POR" IS 'creado por';
   COMMENT ON COLUMN "FUNDAUC"."ESTUDIANTE"."MODIFICADO_POR" IS 'modificado por';
   COMMENT ON TABLE "FUNDAUC"."ESTUDIANTE"  IS 'ESTUDIANTE';
--------------------------------------------------------
--  DDL for Table ESTUDIANTE_RESP
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."ESTUDIANTE_RESP" 
   (	"CEDULA_EST" NUMBER(10,0), 
	"NACIONALIDAD" CHAR(1 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELF_HAB" VARCHAR2(14 BYTE), 
	"TELF_CEL" VARCHAR2(14 BYTE), 
	"CIUDAD" NUMBER(10,0), 
	"ESTADO" NUMBER(10,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"EDO_CIVIL" VARCHAR2(20 BYTE), 
	"GRADO_INS" VARCHAR2(20 BYTE), 
	"PROFESION" NUMBER, 
	"FECHA_NAC" DATE, 
	"STATUS" VARCHAR2(2 BYTE), 
	"ID_TIPO_EST" VARCHAR2(1 BYTE), 
	"RIF" VARCHAR2(16 BYTE), 
	"MATRICULA" NUMBER(10,0), 
	"SEDE" VARCHAR2(3 BYTE), 
	"CONDICION_ESPECIAL" VARCHAR2(2 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"ZONA" NUMBER, 
	"CEDULA_REP" VARCHAR2(16 BYTE), 
	"DIRECCION" VARCHAR2(500 BYTE), 
	"CREADO_POR" VARCHAR2(30 BYTE), 
	"CREADO_EL" DATE, 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"MODIFICADO_EL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table EVENTOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."EVENTOS" 
   (	"ID_EVENTO" NUMBER(4,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"TIPO_EVENTO" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."EVENTOS"."ID_EVENTO" IS 'ID_EVENTO';
   COMMENT ON COLUMN "FUNDAUC"."EVENTOS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."EVENTOS"."TIPO_EVENTO" IS 'TIPO DE EVENTO EJ. ACADEMICO ACAD, ADMINISTRATIVO ADM';
   COMMENT ON TABLE "FUNDAUC"."EVENTOS"  IS 'EVENTOS';
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."FACTURA" 
   (	"ID_FACT" NUMBER(8,0), 
	"TIPO" VARCHAR2(2 BYTE), 
	"CEDULA_EST" NUMBER(10,0), 
	"NOMBRE_CLIENTE" VARCHAR2(100 BYTE), 
	"FECHA_EMI" DATE, 
	"MONTO" NUMBER(14,2), 
	"P_IVA" NUMBER(5,2), 
	"MONTO_IVA" NUMBER(14,2), 
	"FLETE" NUMBER(14,2), 
	"BS_DESCUENTO" NUMBER(14,2), 
	"DIR_FISCAL" VARCHAR2(500 BYTE), 
	"RIF" VARCHAR2(16 BYTE), 
	"STATUS" VARCHAR2(2 BYTE), 
	"PROGRAMA" VARCHAR2(3 BYTE), 
	"PROG_ACADEMICO" NUMBER(2,0), 
	"CREADO_POR" VARCHAR2(30 BYTE), 
	"MONTO_EXENTO" NUMBER(14,2), 
	"BASE_IMPONIBLE" NUMBER(14,2), 
	"ID" NUMBER, 
	"CREADO_EL" DATE DEFAULT SYSDATE, 
	"FACTURADO_POR" VARCHAR2(30 BYTE) DEFAULT coalesce(sys_context('APEX$SESSION', 'app_user'), regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*'), sys_context('userenv', 'session_user')), 
	"OBSERVACIONES" VARCHAR2(2000 BYTE), 
	"ESCREDITO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 983040 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."ID_FACT" IS 'ID_FACT';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."TIPO" IS 'TIPO';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."CEDULA_EST" IS 'CEDULA_EST';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."NOMBRE_CLIENTE" IS 'NOMBRE_CLIENTE';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."FECHA_EMI" IS 'FECHA_EMI';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."MONTO" IS 'MONTO';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."P_IVA" IS 'P_IVA';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."MONTO_IVA" IS 'MONTO_IVA';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."FLETE" IS 'FLETE';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."BS_DESCUENTO" IS 'BS_DESCUENTO';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."DIR_FISCAL" IS 'DIR_FISCAL';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."RIF" IS 'RIF';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."PROGRAMA" IS 'PROGRAMA';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."PROG_ACADEMICO" IS 'PROG_ACADEMICO';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."CREADO_POR" IS 'USUARIO';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."MONTO_EXENTO" IS 'MONTO_EXENTO';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."BASE_IMPONIBLE" IS 'BASE_IMPONIBLE';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."ID" IS 'Identificador unico de Factura';
   COMMENT ON COLUMN "FUNDAUC"."FACTURA"."ESCREDITO" IS 'Si es A credito o al contado';
   COMMENT ON TABLE "FUNDAUC"."FACTURA"  IS 'FACTURA';
--------------------------------------------------------
--  DDL for Table FACTURA_BAK
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."FACTURA_BAK" 
   (	"ID_FACT" NUMBER(8,0), 
	"TIPO" VARCHAR2(2 BYTE), 
	"CEDULA_EST" NUMBER(10,0), 
	"NOMBRE_CLIENTE" VARCHAR2(100 BYTE), 
	"FECHA_EMI" DATE, 
	"MONTO" NUMBER(14,2), 
	"P_IVA" NUMBER(5,2), 
	"MONTO_IVA" NUMBER(14,2), 
	"FLETE" NUMBER(14,2), 
	"BS_DESCUENTO" NUMBER(14,2), 
	"DIR_FISCAL" VARCHAR2(500 BYTE), 
	"RIF" VARCHAR2(16 BYTE), 
	"STATUS" VARCHAR2(2 BYTE), 
	"PROGRAMA" VARCHAR2(3 BYTE), 
	"PROG_ACADEMICO" NUMBER(2,0), 
	"CREADO_POR" VARCHAR2(30 BYTE), 
	"MONTO_EXENTO" NUMBER(14,2), 
	"BASE_IMPONIBLE" NUMBER(14,2), 
	"ID" NUMBER, 
	"CREADO_EL" DATE, 
	"FACTURADO_POR" VARCHAR2(30 BYTE), 
	"OBSERVACIONES" VARCHAR2(2000 BYTE), 
	"INSCRIPCION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table FACTURA_DEPOSITO
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."FACTURA_DEPOSITO" 
   (	"DEPOSITO_ID" NUMBER, 
	"FACTURA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table FORMA_PAGO
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."FORMA_PAGO" 
   (	"ID_PAGO" NUMBER(2,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"VENCIMIENTO" NUMBER(3,0), 
	"TIPO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."FORMA_PAGO"."ID_PAGO" IS 'ID_PAGO';
   COMMENT ON COLUMN "FUNDAUC"."FORMA_PAGO"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."FORMA_PAGO"."VENCIMIENTO" IS 'VENCIMIENTO';
   COMMENT ON COLUMN "FUNDAUC"."FORMA_PAGO"."TIPO" IS 'TIPO';
   COMMENT ON TABLE "FUNDAUC"."FORMA_PAGO"  IS 'FORMA_PAGO';
--------------------------------------------------------
--  DDL for Table GLOBAL_VALUE
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."GLOBAL_VALUE" 
   (	"USR" VARCHAR2(255 BYTE), 
	"VAR" VARCHAR2(100 BYTE), 
	"VALUE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table HOJA_VIDA_EST
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."HOJA_VIDA_EST" 
   (	"ID" NUMBER, 
	"MATRICULA" NUMBER, 
	"EVENTO_ID" NUMBER, 
	"FECHA" TIMESTAMP (6) DEFAULT systimestamp, 
	"METADATA" CLOB, 
	"OBSERVACION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "FUNDAUC" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table HOJA_VIDA_EST_BK
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."HOJA_VIDA_EST_BK" 
   (	"ID" NUMBER, 
	"MATRICULA" NUMBER, 
	"EVENTO_ID" NUMBER, 
	"FECHA" TIMESTAMP (6) DEFAULT systimestamp, 
	"METADATA" CLOB, 
	"OBSERVACION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "FUNDAUC" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table HORARIOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."HORARIOS" 
   (	"ID_HORARIO" NUMBER(10,0), 
	"HORA" DATE, 
	"MODALIDAD" NUMBER(3,0), 
	"HORA_FIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."HORARIOS"."ID_HORARIO" IS 'ID_HORARIO';
   COMMENT ON COLUMN "FUNDAUC"."HORARIOS"."HORA" IS 'HORA';
   COMMENT ON COLUMN "FUNDAUC"."HORARIOS"."MODALIDAD" IS 'MODALIDAD';
   COMMENT ON COLUMN "FUNDAUC"."HORARIOS"."HORA_FIN" IS 'HORA_FIN';
   COMMENT ON TABLE "FUNDAUC"."HORARIOS"  IS 'HORARIOS';
--------------------------------------------------------
--  DDL for Table INSCRIPCIONES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."INSCRIPCIONES" 
   (	"ID" NUMBER, 
	"FECHA_INS" TIMESTAMP (6) DEFAULT systimestamp, 
	"EST_MATRICULA" NUMBER(10,0), 
	"FECHA_PAGO" DATE, 
	"ESTATUS" VARCHAR2(255 BYTE), 
	"SECCION_ID" NUMBER, 
	"PERIODO_ID" NUMBER, 
	"CREADO_POR" VARCHAR2(255 BYTE) DEFAULT coalesce(sys_context('APEX$SESSION', 'app_user'), regexp_substr(sys_context('userenv', 'client_identifier'
    ), '^[^:]*'), sys_context('userenv', 'session_user')), 
	"ES_EXONERADO" CHAR(1 BYTE) DEFAULT 'N', 
	"PROG_ACADEMICO" NUMBER, 
	"ES_SUSPENDIDO" CHAR(1 BYTE) DEFAULT 'N', 
	"COHORTE_ID" NUMBER, 
	"HORARIO_ID" NUMBER, 
	"MODIFICADO_POR" VARCHAR2(255 BYTE), 
	"MODIFICADO_EL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."ID" IS 'Identificador unico de la iscripcion del estudiante en el curso';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."FECHA_INS" IS 'Fecha de la Inscripcion';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."EST_MATRICULA" IS 'MAtricula Estudiante';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."FECHA_PAGO" IS 'Fecha de Pago de la Inscripcion';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."ESTATUS" IS 'Estado de laInscripcion Ej, Pre-Inscripcion, Inscripcion Efectiva, Inscripcion Anulada, Inscripcion Exonerada, Inactiva';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."SECCION_ID" IS 'Identificador Unico de la Seccion';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."PERIODO_ID" IS 'Pediodo de Inscripcion';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."CREADO_POR" IS 'Usuario quien creo la Inscripcion';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."ES_EXONERADO" IS 'Si esestudiante es exonerado o no';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."PROG_ACADEMICO" IS 'Programa Academico';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."ES_SUSPENDIDO" IS 'Si el Estudiante Suspendio un curso o no';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."COHORTE_ID" IS 'Cohorte id';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."HORARIO_ID" IS 'Id del horario de Inscripcion';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."MODIFICADO_POR" IS 'Quien modifico el registro';
   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCIONES"."MODIFICADO_EL" IS 'Cuando se Modifico el Registro';
   COMMENT ON TABLE "FUNDAUC"."INSCRIPCIONES"  IS 'Tabla de Inscripciones';
--------------------------------------------------------
--  DDL for Table INSCRIPCIONES_BAK
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."INSCRIPCIONES_BAK" 
   (	"ID" NUMBER, 
	"FECHA_INS" TIMESTAMP (6), 
	"EST_MATRICULA" NUMBER(10,0), 
	"FECHA_PAGO" DATE, 
	"ESTATUS" VARCHAR2(255 BYTE), 
	"SECCION_ID" NUMBER, 
	"PERIODO_ID" NUMBER, 
	"CREADO_POR" VARCHAR2(255 BYTE), 
	"ES_EXONERADO" CHAR(1 BYTE), 
	"PROG_ACADEMICO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table INSCRIPCIONES_HIS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."INSCRIPCIONES_HIS" 
   (	"ID" NUMBER, 
	"FECHA_INS" TIMESTAMP (6), 
	"EST_MATRICULA" NUMBER(10,0), 
	"FECHA_PAGO" DATE, 
	"ESTATUS" VARCHAR2(255 BYTE), 
	"SECCION_ID" NUMBER, 
	"FACTURA_ID" NUMBER, 
	"CREADO_POR" VARCHAR2(255 BYTE), 
	"ES_EXONERADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table INSCRIPCIONES_RESP
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."INSCRIPCIONES_RESP" 
   (	"ID" NUMBER, 
	"FECHA_INS" TIMESTAMP (6), 
	"EST_MATRICULA" NUMBER(10,0), 
	"FECHA_PAGO" DATE, 
	"ESTATUS" VARCHAR2(255 BYTE), 
	"SECCION_ID" NUMBER, 
	"FACTURA_ID" NUMBER, 
	"CREADO_POR" VARCHAR2(255 BYTE), 
	"ES_EXONERADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table INSCRIPCION_FACTURA
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."INSCRIPCION_FACTURA" 
   (	"INSCRIPCION_ID" NUMBER, 
	"FACTURA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."INSCRIPCION_FACTURA"."INSCRIPCION_ID" IS 'Id de la inscripcion';
--------------------------------------------------------
--  DDL for Table INSTANCIAS_SECCIONES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."INSTANCIAS_SECCIONES" 
   (	"ID" NUMBER, 
	"SECCION_ID" NUMBER, 
	"CODIGO_SEC" VARCHAR2(50 BYTE), 
	"METODO_ID" VARCHAR2(20 BYTE), 
	"NIVEL" NUMBER(2,0), 
	"PERIODO_ID" NUMBER, 
	"HORARIO_ID" NUMBER, 
	"MODALIDAD_ID" NUMBER, 
	"CEDULA_PROF" VARCHAR2(20 BYTE), 
	"F_INICIO" DATE, 
	"F_FIN" DATE, 
	"ESTATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."INSTANCIAS_SECCIONES"."ID" IS 'Identificador Unico de Instancia de Seccion';
   COMMENT ON COLUMN "FUNDAUC"."INSTANCIAS_SECCIONES"."SECCION_ID" IS 'Identificador unico de la seccion';
   COMMENT ON COLUMN "FUNDAUC"."INSTANCIAS_SECCIONES"."CODIGO_SEC" IS 'Codigo de la Seccion';
   COMMENT ON COLUMN "FUNDAUC"."INSTANCIAS_SECCIONES"."METODO_ID" IS 'identificador unco del metodo';
--------------------------------------------------------
--  DDL for Table JOB_LOG
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."JOB_LOG" 
   (	"LOG_ID" NUMBER(9,0), 
	"LOG_MESSAGE" VARCHAR2(1000 BYTE), 
	"LOG_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table MATERIALES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."MATERIALES" 
   (	"ID_MAT" VARCHAR2(50 BYTE), 
	"TIPO" VARCHAR2(3 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ID_CURSO" VARCHAR2(10 BYTE), 
	"EVENTO" NUMBER(2,0), 
	"NIVEL" NUMBER(2,0), 
	"IVA_EXENTO" CHAR(1 BYTE) DEFAULT 'S', 
	"ACTIVO" CHAR(1 BYTE) DEFAULT 'S', 
	"ID" NUMBER, 
	"SECCION_ID" NUMBER, 
	"CREADO_POR" VARCHAR2(255 BYTE) DEFAULT coalesce(sys_context('APEX$SESSION', 'app_user'), regexp_substr(sys_context('userenv', 'client_identifier'
    ), '^[^:]*'), sys_context('userenv', 'session_user')), 
	"CREADO_EL" DATE DEFAULT SYSDATE, 
	"MODIFICADO_POR" VARCHAR2(255 BYTE), 
	"MODIFICADO_EL" DATE, 
	"COHORTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."ID_MAT" IS 'ID_MAT';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."TIPO" IS 'TIPO';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."ID_CURSO" IS 'ID_CURSO';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."EVENTO" IS 'EVENTO';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."NIVEL" IS 'NIVEL';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."IVA_EXENTO" IS 'IVA_EXENTO';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."ACTIVO" IS 'ACTIVO';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."ID" IS 'Identificador unico de material';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."SECCION_ID" IS 'Identificador Unico de Seccion';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."CREADO_POR" IS 'Usuario quien creo el material';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."CREADO_EL" IS 'Fecha en que se creo el material';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."MODIFICADO_POR" IS 'Usuario quien modifico el material';
   COMMENT ON COLUMN "FUNDAUC"."MATERIALES"."MODIFICADO_EL" IS 'fecha cuando se modifico el material';
   COMMENT ON TABLE "FUNDAUC"."MATERIALES"  IS 'MATERIALES';
--------------------------------------------------------
--  DDL for Table METODOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."METODOS" 
   (	"ID_METODO" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(80 BYTE), 
	"IDIOMA" VARCHAR2(30 BYTE), 
	"NIVELES" NUMBER(2,0), 
	"EVALUACIONES" NUMBER(2,0), 
	"DIURNO" CHAR(1 BYTE), 
	"NOCTURNO" CHAR(1 BYTE), 
	"SABATINO" CHAR(1 BYTE), 
	"ID_CALENDARIO" NUMBER(2,0), 
	"PROG_ACADEMICO" NUMBER(2,0), 
	"CUOTAS" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."METODOS"."ID_METODO" IS 'ID_METODO';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."IDIOMA" IS 'IDIOMA';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."NIVELES" IS 'NIVELES';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."EVALUACIONES" IS 'EVALUACIONES';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."DIURNO" IS 'DIURNO';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."NOCTURNO" IS 'NOCTURNO';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."SABATINO" IS 'SABATINO';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."ID_CALENDARIO" IS 'ID_CALENDARIO';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."PROG_ACADEMICO" IS 'PROG_ACADEMICO';
   COMMENT ON COLUMN "FUNDAUC"."METODOS"."CUOTAS" IS 'CUOTAS';
   COMMENT ON TABLE "FUNDAUC"."METODOS"  IS 'METODOS';
--------------------------------------------------------
--  DDL for Table MODALIDADES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."MODALIDADES" 
   (	"ID_MODALIDAD" NUMBER(2,0), 
	"DESCRIPCION" VARCHAR2(25 BYTE), 
	"DIAS" VARCHAR2(50 BYTE), 
	"SIGLAS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."MODALIDADES"."ID_MODALIDAD" IS 'ID_MODALIDAD';
   COMMENT ON COLUMN "FUNDAUC"."MODALIDADES"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."MODALIDADES"."SIGLAS" IS 'SIGLAS DE DIAS EN LETRAS';
   COMMENT ON TABLE "FUNDAUC"."MODALIDADES"  IS 'MODALIDADES';
--------------------------------------------------------
--  DDL for Table OCUPACIONES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."OCUPACIONES" 
   (	"ID_OCUPACION" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."OCUPACIONES"."ID_OCUPACION" IS 'ID_OCUPACION';
   COMMENT ON COLUMN "FUNDAUC"."OCUPACIONES"."NOMBRE" IS 'NOMBRE';
   COMMENT ON TABLE "FUNDAUC"."OCUPACIONES"  IS 'OCUPACIONES';
--------------------------------------------------------
--  DDL for Table PRECIOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."PRECIOS" 
   (	"TIPO_ITEM" VARCHAR2(2 BYTE), 
	"FECHA" DATE, 
	"PRECIO1" NUMBER(14,2), 
	"PRECIO2" NUMBER(14,2), 
	"PRECIO3" NUMBER(14,2), 
	"STATUS" VARCHAR2(1 BYTE), 
	"PRECIO4" NUMBER(14,2), 
	"PRECIO5" NUMBER(14,2), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."TIPO_ITEM" IS 'TIPO_ITEM';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."FECHA" IS 'FECHA';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."PRECIO1" IS 'PRECIO1';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."PRECIO2" IS 'PRECIO2';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."PRECIO3" IS 'PRECIO3';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."PRECIO4" IS 'PRECIO4';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."PRECIO5" IS 'PRECIO5';
   COMMENT ON COLUMN "FUNDAUC"."PRECIOS"."ID" IS 'ID PRECIO';
   COMMENT ON TABLE "FUNDAUC"."PRECIOS"  IS 'PRECIOS';
--------------------------------------------------------
--  DDL for Table PROFESOR
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."PROFESOR" 
   (	"CEDULA_PROF" NUMBER(10,0), 
	"NACIONALIDAD" CHAR(1 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TELF_HAB" VARCHAR2(14 BYTE), 
	"TELF_CEL" VARCHAR2(14 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"EDO_CIVIL" CHAR(1 BYTE), 
	"GRADO_INS" CHAR(1 BYTE), 
	"PROFESION" VARCHAR2(20 BYTE), 
	"FECHA_NAC" DATE, 
	"STATUS" VARCHAR2(2 BYTE), 
	"ID_TIPO_PROF" VARCHAR2(1 BYTE), 
	"RIF" VARCHAR2(16 BYTE), 
	"SEDE" VARCHAR2(3 BYTE), 
	"APELLIDO" VARCHAR2(25 BYTE), 
	"ZONA" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."CEDULA_PROF" IS 'CEDULA_PROF';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."NACIONALIDAD" IS 'NACIONALIDAD';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."NOMBRE" IS 'NOMBRE';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."TELF_HAB" IS 'TELF_HAB';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."TELF_CEL" IS 'TELF_CEL';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."CIUDAD" IS 'CIUDAD';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."ESTADO" IS 'ESTADO';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."EMAIL" IS 'EMAIL';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."SEXO" IS 'SEXO';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."EDO_CIVIL" IS 'EDO_CIVIL';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."GRADO_INS" IS 'GRADO_INS';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."PROFESION" IS 'PROFESION';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."FECHA_NAC" IS 'FECHA_NAC';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."ID_TIPO_PROF" IS 'ID_TIPO_PROF';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."RIF" IS 'RIF';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."SEDE" IS 'SEDE';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."APELLIDO" IS 'APELLIDO';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."ZONA" IS 'ZONA';
   COMMENT ON COLUMN "FUNDAUC"."PROFESOR"."DIRECCION" IS 'DIRECCION';
   COMMENT ON TABLE "FUNDAUC"."PROFESOR"  IS 'PROFESOR';
--------------------------------------------------------
--  DDL for Table PROGRAMA_ACADEMICO
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."PROGRAMA_ACADEMICO" 
   (	"ID" NUMBER(2,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"ACTIVO" CHAR(1 BYTE) DEFAULT 'S'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."PROGRAMA_ACADEMICO"."ID" IS 'ID';
   COMMENT ON COLUMN "FUNDAUC"."PROGRAMA_ACADEMICO"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."PROGRAMA_ACADEMICO"."ACTIVO" IS 'ACTIVO';
   COMMENT ON TABLE "FUNDAUC"."PROGRAMA_ACADEMICO"  IS 'PROGRAMA_ACADEMICO';
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."ROLES" 
   (	"ID_ROL" NUMBER(3,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."ROLES"."ID_ROL" IS 'ID_ROL';
   COMMENT ON COLUMN "FUNDAUC"."ROLES"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON TABLE "FUNDAUC"."ROLES"  IS 'ROLES';
--------------------------------------------------------
--  DDL for Table SALONES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."SALONES" 
   (	"ID_SALON" NUMBER(3,0), 
	"EDIFICIO" NUMBER(3,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"CAPACIDAD" NUMBER(3,0), 
	"ANCHO" NUMBER(4,0), 
	"LARGO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."SALONES"."ID_SALON" IS 'ID_SALON';
   COMMENT ON COLUMN "FUNDAUC"."SALONES"."EDIFICIO" IS 'EDIFICIO';
   COMMENT ON COLUMN "FUNDAUC"."SALONES"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."SALONES"."CAPACIDAD" IS 'CAPACIDAD';
   COMMENT ON COLUMN "FUNDAUC"."SALONES"."ANCHO" IS 'ANCHO';
   COMMENT ON COLUMN "FUNDAUC"."SALONES"."LARGO" IS 'LARGO';
   COMMENT ON TABLE "FUNDAUC"."SALONES"  IS 'SALONES';
--------------------------------------------------------
--  DDL for Table SECCIONES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."SECCIONES" 
   (	"ID_SECCION" VARCHAR2(50 BYTE), 
	"ID_METODO" VARCHAR2(10 BYTE), 
	"NIVEL" NUMBER(2,0), 
	"ID_SALON" NUMBER(3,0), 
	"TOPE" NUMBER(2,0), 
	"STATUS" CHAR(1 BYTE), 
	"ID_EDIF" NUMBER(3,0), 
	"HORARIO" VARCHAR2(17 BYTE), 
	"CEDULA_PROF" NUMBER(10,0), 
	"MODALIDAD" NUMBER(3,0), 
	"FEC_INICIO" DATE, 
	"PERIODO" NUMBER, 
	"ID_HORARIO" NUMBER(3,0), 
	"ID_CALENDARIO" NUMBER, 
	"ID" NUMBER, 
	"CREADO_POR" VARCHAR2(255 BYTE), 
	"CREADO_EL" DATE, 
	"MODIFICADO_POR" VARCHAR2(255 BYTE), 
	"MODIFICADO_EL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."ID_SECCION" IS 'ID_SECCION';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."ID_METODO" IS 'ID_METODO';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."NIVEL" IS 'NIVEL';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."ID_SALON" IS 'ID_SALON';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."TOPE" IS 'TOPE';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."STATUS" IS 'STATUS';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."ID_EDIF" IS 'ID_EDIF';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."HORARIO" IS 'HORARIO';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."CEDULA_PROF" IS 'CEDULA_PROF';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."MODALIDAD" IS 'MODALIDAD';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."FEC_INICIO" IS 'FEC_INICIO';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."PERIODO" IS 'PERIODO';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."ID" IS 'Identificador Unico de la Seccion';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."CREADO_POR" IS 'usuario quien crea la seccion';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."CREADO_EL" IS 'Fecha de Creacion';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."MODIFICADO_POR" IS 'usuario quien modifica la seccion';
   COMMENT ON COLUMN "FUNDAUC"."SECCIONES"."MODIFICADO_EL" IS 'Fecha de Modificacion';
   COMMENT ON TABLE "FUNDAUC"."SECCIONES"  IS 'SECCIONES';
--------------------------------------------------------
--  DDL for Table SECCIONES_BAK
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."SECCIONES_BAK" 
   (	"ID_SECCION" VARCHAR2(50 BYTE), 
	"ID_METODO" VARCHAR2(10 BYTE), 
	"NIVEL" NUMBER(2,0), 
	"ID_SALON" NUMBER(3,0), 
	"TOPE" NUMBER(2,0), 
	"STATUS" CHAR(1 BYTE), 
	"ID_EDIF" NUMBER(3,0), 
	"HORARIO" VARCHAR2(17 BYTE), 
	"CEDULA_PROF" NUMBER(10,0), 
	"MODALIDAD" NUMBER(3,0), 
	"FEC_INICIO" DATE, 
	"PERIODO" NUMBER, 
	"ID_HORARIO" NUMBER(3,0), 
	"ID_CALENDARIO" NUMBER, 
	"ID" NUMBER, 
	"CREADO_POR" VARCHAR2(255 BYTE), 
	"CREADO_EL" DATE, 
	"MODIFICADO_POR" VARCHAR2(255 BYTE), 
	"MODIFICADO_EL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table TE_TEMPLATES
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."TE_TEMPLATES" 
   (	"NAME" VARCHAR2(300 BYTE), 
	"TEMPLATE" CLOB, 
	"DESCRIPTION" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE) DEFAULT user, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE) DEFAULT user, 
	"MODIFIED_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FUNDAUC" 
 LOB ("TEMPLATE") STORE AS SECUREFILE (
  TABLESPACE "FUNDAUC" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table TIPO_ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."TIPO_ESTUDIANTE" 
   (	"ID_TIPO_EST" VARCHAR2(1 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."TIPO_ESTUDIANTE"."ID_TIPO_EST" IS 'ID_TIPO_EST';
   COMMENT ON COLUMN "FUNDAUC"."TIPO_ESTUDIANTE"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON TABLE "FUNDAUC"."TIPO_ESTUDIANTE"  IS 'TIPO_ESTUDIANTE';
--------------------------------------------------------
--  DDL for Table TIPO_MATERIAL
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."TIPO_MATERIAL" 
   (	"ABREV" VARCHAR2(3 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"IDIOMAS" CHAR(1 BYTE), 
	"CTC" CHAR(1 BYTE), 
	"CFP" CHAR(1 BYTE), 
	"USA_SECCION" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."TIPO_MATERIAL"."ABREV" IS 'ABREV';
   COMMENT ON COLUMN "FUNDAUC"."TIPO_MATERIAL"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."TIPO_MATERIAL"."IDIOMAS" IS 'IDIOMAS';
   COMMENT ON COLUMN "FUNDAUC"."TIPO_MATERIAL"."CTC" IS 'CTC';
   COMMENT ON COLUMN "FUNDAUC"."TIPO_MATERIAL"."CFP" IS 'CFP';
   COMMENT ON COLUMN "FUNDAUC"."TIPO_MATERIAL"."USA_SECCION" IS 'FVTC';
   COMMENT ON TABLE "FUNDAUC"."TIPO_MATERIAL"  IS 'TIPO_MATERIAL';
--------------------------------------------------------
--  DDL for Table TIPO_PROFESOR
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."TIPO_PROFESOR" 
   (	"ID_TIPO_PROF" VARCHAR2(1 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."USUARIOS" 
   (	"CEDULA" NUMBER(10,0), 
	"NOMBRE_USUARIO" VARCHAR2(50 BYTE), 
	"CONTRASENA" VARCHAR2(255 BYTE), 
	"ID_ROL" NUMBER(3,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CIA" NUMBER(2,0), 
	"PROG_ACADEMICO" NUMBER(2,0), 
	"ACTIVO" CHAR(1 BYTE) DEFAULT 'S', 
	"BLOQUEADO" CHAR(1 BYTE) DEFAULT 'N', 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"CREADO_EL" DATE DEFAULT SYSDATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"MODIFICADO_EL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."CEDULA" IS 'CEDULA';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."NOMBRE_USUARIO" IS 'NOMBRE_USUARIO';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."CONTRASENA" IS 'CONTRASENA';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."ID_ROL" IS 'ID_ROL';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."EMAIL" IS 'EMAIL';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."NOMBRE" IS 'NOMBRE';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."CIA" IS 'CIA';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."PROG_ACADEMICO" IS 'PROG_ACADEMICO';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."BLOQUEADO" IS 'Usuario Bloqueado?';
   COMMENT ON COLUMN "FUNDAUC"."USUARIOS"."CREADO_EL" IS 'fecha de creacion del usuario';
   COMMENT ON TABLE "FUNDAUC"."USUARIOS"  IS 'USUARIOS';
--------------------------------------------------------
--  DDL for Table ZONAS
--------------------------------------------------------

  CREATE TABLE "FUNDAUC"."ZONAS" 
   (	"ID_ZONA" NUMBER, 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"ID_CIUDAD" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FUNDAUC" ;

   COMMENT ON COLUMN "FUNDAUC"."ZONAS"."ID_ZONA" IS 'ID_ZONA';
   COMMENT ON COLUMN "FUNDAUC"."ZONAS"."DESCRIPCION" IS 'DESCRIPCION';
   COMMENT ON COLUMN "FUNDAUC"."ZONAS"."ID_CIUDAD" IS 'ID_CIUDAD';
   COMMENT ON TABLE "FUNDAUC"."ZONAS"  IS 'ZONAS';
